development:
  adapter: postgresql
  encoding: utf8
  database: prism_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: prism_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: prism_production
  pool: 5
  username: 
  password: